### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by KingCocoIsh**

### CODE REVIEW

**Review by PhantomW0rm — APPROVED** [review]
perfect

**Review by PhantomW0rm — APPROVED** [review]
Thank you ismail

**Review by WillSped — APPROVED** [review]
quality

**Review by PhantomW0rm — APPROVED** [review]

**Review by dannycraigie — COMMENTED** [review]
:-(

**Review by dannycraigie — APPROVED** [review]

**Pull request merged**
